In [3]:
import pandas as pd #Covert list of list data in dataframe
data = [["Harry",35],["Mohan",65],["Rajeev",29],["Siddhi",35],["Kirti",19]]
df = pd.DataFrame(data,columns = ["Name","marks"])
df

     Name  marks
0   Harry     35
1   Mohan     65
2  Rajeev     29
3  Siddhi     35
4   Kirti     19

In [4]:
dictionary = { "A":[2,3,4],"B":[3,4,5]}#Convert dictionary data into data frames
dictionary

{'A': [2, 3, 4], 'B': [3, 4, 5]}

In [6]:
df = pd.DataFrame(dictionary)
df

   A  B
0  2  3
1  3  4
2  4  5

In [7]:
import numpy as np #Convert numpy array data into dataframe
arr = np.array([[2,4],[5,6]])
df = pd.DataFrame(arr,columns= ["A","B"])
df

   A  B
0  2  4
1  5  6